version: '3.7'
services:
  mysql:
    container_name: horse-mysql
    image: mysql:5.7
    ports: ['33066:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  php:
    container_name: horse-php
    build: ./docker/php
    ports: ['9000:9001']
    links:
      - mysql
    volumes:
      - ./www/:/var/www:cached
  nginx:
    container_name: horse-nginx
    build: ./docker/nginx
    ports: ['8080:80']
    links:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - ./www/:/var/www:cached